version: '3.5'

services:
    localstack:
        image: localstack/localstack
        container_name: lambda-localstack
        ports:
            - "4567-4599:4567-4599"
            - 8081:8080
        networks: 
            - localstack-network
        environment:
            - SERVICES=s3,lambda,iam,dynamodb
            - DEFAULT_REGION=eu-west-1
            - DOCKER_HOST=unix:///var/run/docker.sock
            - LAMBDA_REMOVE_CONTAINERS=true
            - LAMBDA_DOCKER_NETWORK=localstack-network
            - LAMBDA_EXECUTOR=docker
            - SETUP_ROOT_FOLDER=/mnt/setup
            - DATA_ROOT_FOLDER=/mnt/data
        volumes: 
            - ./setup:/docker-entrypoint-initaws.d
            - ./setup:/mnt/setup
            - ./data:/mnt/data
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    localstack-network:
        name: localstack-network