version: "3.5"

services: 
  localstack:
    image: localstack/localstack:latest
    networks:
      - network
    container_name: localstack
    environment:
    - SERVICES=sqs,sns,dynamodb
    - DEFAULT_REGION=eu-west-1
    - DYNAMODB_ERROR_PROBABILITY=0.01
    ports:
    - "4575:4575"
    - "4576:4576"
    - "4569:4569"
    - "8080:8080"
  
  # awscli:
  #   image: garland/aws-cli-docker:latest
  #   container_name: awscli
  #   networks:
  #     - network
  #   depends_on:
  #     - localstack 
  #   volumes:
  #     - type: bind
  #       source: ./local
  #       target: /data
  #   environment:
  #   - AWS_DEFAULT_REGION=eu-west-1
  #   - AWS_ACCESS_KEY_ID=XX
  #   - AWS_SECRET_ACCESS_KEY=XX
  #   command:
  #   - /bin/sh
  #   - -c
  #   - |
  #       echo Waiting 15s for Dynamo Db to start
  #       sleep 15
        
networks:
  network:
    name: network